[2025-09-18T09:25:10.600+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-18T09:25:11.057+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 3_logistics_gold_metrics_dbt.dbt_run_gold manual__2025-09-18T09:17:55.038724+00:00 [queued]>
[2025-09-18T09:25:11.120+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 3_logistics_gold_metrics_dbt.dbt_run_gold manual__2025-09-18T09:17:55.038724+00:00 [queued]>
[2025-09-18T09:25:11.121+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-18T09:25:11.340+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run_gold> on 2025-09-18 09:17:55.038724+00:00
[2025-09-18T09:25:11.370+0000] {standard_task_runner.py:63} INFO - Started process 2978 to run task
[2025-09-18T09:25:11.451+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', '3_logistics_gold_metrics_dbt', 'dbt_run_gold', 'manual__2025-09-18T09:17:55.038724+00:00', '--job-id', '1083', '--raw', '--subdir', 'DAGS_FOLDER/3_logistics-gold-metrics-dbt.py', '--cfg-path', '/tmp/tmpa35drahb']
[2025-09-18T09:25:11.613+0000] {standard_task_runner.py:91} INFO - Job 1083: Subtask dbt_run_gold
[2025-09-18T09:25:12.279+0000] {task_command.py:426} INFO - Running <TaskInstance: 3_logistics_gold_metrics_dbt.dbt_run_gold manual__2025-09-18T09:17:55.038724+00:00 [running]> on host 9d1b71842418
[2025-09-18T09:25:14.934+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_eng' AIRFLOW_CTX_DAG_ID='3_logistics_gold_metrics_dbt' AIRFLOW_CTX_TASK_ID='dbt_run_gold' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T09:17:55.038724+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T09:17:55.038724+00:00'
[2025-09-18T09:25:14.941+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-18T09:25:15.193+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-18T09:25:15.201+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/airflow/dbt/dbt-project && dbt run --select path:models/gold/']
[2025-09-18T09:25:15.478+0000] {subprocess.py:86} INFO - Output:
[2025-09-18T09:25:51.911+0000] {subprocess.py:93} INFO - [0m09:25:51  Running with dbt=1.8.8
[2025-09-18T09:26:00.531+0000] {subprocess.py:93} INFO - [0m09:26:00  Registered adapter: snowflake=1.8.4
[2025-09-18T09:26:40.332+0000] {subprocess.py:93} INFO - [0m09:26:40  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-09-18T09:26:40.334+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-09-18T09:26:40.339+0000] {subprocess.py:93} INFO - - snapshots.customers
[2025-09-18T09:26:45.730+0000] {subprocess.py:93} INFO - [0m09:26:45  Found 18 models, 1 snapshot, 1 seed, 24 data tests, 8 sources, 726 macros
[2025-09-18T09:26:46.256+0000] {subprocess.py:93} INFO - [0m09:26:46
[2025-09-18T09:27:03.579+0000] {subprocess.py:93} INFO - [0m09:27:03  Concurrency: 3 threads (target='dev')
[2025-09-18T09:27:03.691+0000] {subprocess.py:93} INFO - [0m09:27:03
[2025-09-18T09:27:03.981+0000] {subprocess.py:93} INFO - [0m09:27:03  1 of 8 START sql table model gold.customer_experience_summary .................. [RUN]
[2025-09-18T09:27:04.058+0000] {subprocess.py:93} INFO - [0m09:27:04  3 of 8 START sql view model gold.delivery_sla_rootcause ........................ [RUN]
[2025-09-18T09:27:04.071+0000] {subprocess.py:93} INFO - [0m09:27:04  2 of 8 START sql view model gold.delivery_performance_by_courier ............... [RUN]
[2025-09-18T09:27:10.557+0000] {subprocess.py:93} INFO - [0m09:27:10  3 of 8 OK created sql view model gold.delivery_sla_rootcause ................... [[32mSUCCESS 1[0m in 6.40s]
[2025-09-18T09:27:10.710+0000] {subprocess.py:93} INFO - [0m09:27:10  1 of 8 ERROR creating sql table model gold.customer_experience_summary ......... [[31mERROR[0m in 6.57s]
[2025-09-18T09:27:10.861+0000] {subprocess.py:93} INFO - [0m09:27:10  4 of 8 START sql table model gold.dm_inventory_status .......................... [RUN]
[2025-09-18T09:27:11.002+0000] {subprocess.py:93} INFO - [0m09:27:11  5 of 8 START sql table model gold.dm_order_fulfillment ......................... [RUN]
[2025-09-18T09:27:11.254+0000] {subprocess.py:93} INFO - [0m09:27:11  2 of 8 OK created sql view model gold.delivery_performance_by_courier .......... [[32mSUCCESS 1[0m in 7.11s]
[2025-09-18T09:27:11.340+0000] {subprocess.py:93} INFO - [0m09:27:11  6 of 8 START sql table model gold.order_to_delivery_lifecycle .................. [RUN]
[2025-09-18T09:27:15.348+0000] {subprocess.py:93} INFO - [0m09:27:15  5 of 8 OK created sql table model gold.dm_order_fulfillment .................... [[32mSUCCESS 1[0m in 4.26s]
[2025-09-18T09:27:15.368+0000] {subprocess.py:93} INFO - [0m09:27:15  7 of 8 START sql table model gold.seller_performance ........................... [RUN]
[2025-09-18T09:27:15.786+0000] {subprocess.py:93} INFO - [0m09:27:15  6 of 8 OK created sql table model gold.order_to_delivery_lifecycle ............. [[32mSUCCESS 1[0m in 4.35s]
[2025-09-18T09:27:15.905+0000] {subprocess.py:93} INFO - [0m09:27:15  8 of 8 START sql view model gold.seller_product_profitability .................. [RUN]
[2025-09-18T09:27:16.008+0000] {subprocess.py:93} INFO - [0m09:27:16  4 of 8 OK created sql table model gold.dm_inventory_status ..................... [[32mSUCCESS 1[0m in 5.01s]
[2025-09-18T09:27:18.669+0000] {subprocess.py:93} INFO - [0m09:27:18  7 of 8 OK created sql table model gold.seller_performance ...................... [[32mSUCCESS 1[0m in 3.23s]
[2025-09-18T09:27:19.572+0000] {subprocess.py:93} INFO - [0m09:27:19  8 of 8 OK created sql view model gold.seller_product_profitability ............. [[32mSUCCESS 1[0m in 3.51s]
[2025-09-18T09:27:20.284+0000] {subprocess.py:93} INFO - [0m09:27:20
[2025-09-18T09:27:20.299+0000] {subprocess.py:93} INFO - [0m09:27:20  Finished running 3 view models, 5 table models in 0 hours 0 minutes and 33.76 seconds (33.76s).
[2025-09-18T09:27:24.957+0000] {subprocess.py:93} INFO - [0m09:27:24
[2025-09-18T09:27:25.108+0000] {subprocess.py:93} INFO - [0m09:27:25  [31mCompleted with 1 error and 0 warnings:[0m
[2025-09-18T09:27:25.174+0000] {subprocess.py:93} INFO - [0m09:27:25
[2025-09-18T09:27:25.240+0000] {subprocess.py:93} INFO - [0m09:27:25    Database Error in model customer_experience_summary (models/gold/customer_experience_summary.sql)
[2025-09-18T09:27:25.274+0000] {subprocess.py:93} INFO -   002003 (42S02): SQL compilation error:
[2025-09-18T09:27:25.345+0000] {subprocess.py:93} INFO -   Object 'LOGISTICS_DEMO_1.GOLD.CONTROL_TABLE' does not exist or not authorized.
[2025-09-18T09:27:25.375+0000] {subprocess.py:93} INFO -   compiled code at target/run/logistics_project/models/gold/customer_experience_summary.sql
[2025-09-18T09:27:25.438+0000] {subprocess.py:93} INFO - [0m09:27:25
[2025-09-18T09:27:25.506+0000] {subprocess.py:93} INFO - [0m09:27:25  Done. PASS=7 WARN=0 ERROR=1 SKIP=0 TOTAL=8
[2025-09-18T09:27:33.288+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-18T09:27:33.304+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-18T09:27:33.684+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-18T09:27:33.909+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=3_logistics_gold_metrics_dbt, task_id=dbt_run_gold, run_id=manual__2025-09-18T09:17:55.038724+00:00, execution_date=20250918T091755, start_date=20250918T092511, end_date=20250918T092733
[2025-09-18T09:27:38.052+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1083 for task dbt_run_gold (Bash command failed. The command returned a non-zero exit code 1.; 2978)
[2025-09-18T09:27:38.112+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-18T09:27:38.670+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-18T09:27:38.692+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
